[package]
name = "coconut"
version = "0.1.0"
authors = ["Amir Taaki <amir@dyne.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
sha2 = "0.8.0"
hex-slice = "0.1.4"
bls12_381 = { version = "0.1.0", path = "../bls12_381" }
#bls12_381 = { git = "https://github.com/zkcrypto/bls12_381" }

